name: Deploy Static Site

on:
  push:
    branches:
      - master  # Change to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}  # Only IP, no '-p 22'
          username: ${{ secrets.SERVER_USER }}  # Store separately in GitHub Secrets
          password: ${{ secrets.SERVER_PASSWORD }}  # Store password in GitHub Secrets
          port: 22  # Specify port separately
          source: "."  # Files to upload
          target: "/var/www/personal-portfolio"  # Destination on the server
