name: Deploy Static Site

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}  
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "./*"  # Upload only necessary files (avoid hidden files)
          target: "/var/www/personal-portfolio"
          rm: true  # Removes old files before uploading
          overwrite: true  # Overwrites existing files
